apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      # Salto desde un span -> logs Loki filtrados por traceId.
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        filterByTraceID: true
        customQuery: true
        query: '{container=~".*backend.*"} | json | traceId="$${__span.traceId}"'
      # Botón "Service graph" si llega a usarse Tempo metrics-generator.
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
